script = *( function-expression / function (";" / 2strong-separator ) / comment / separator)

strong-separator = [CR] LF
sep = 1*WSP / function-separator

comment = "#" *( VCHAR - (strong-separator) ) strong-separator

expression = function-expression / literal / variable / evaluate
function-expression = "(" *sep function *sep ")"
function = identifier [ sep expression *(sep expression) ]

; string
literal = DQUOTE *OCTET DQUOTE / *( ALPHA / DIGIT / "-" / "_" / "." )
; number
literal =/ 1*DIGIT
; bool
literal =/ "true" / "false"
; list
literal =/ "[" *sep [ expression *( 1*sep expression ) ] *sep "]"
; empty
literal =/ "()"

identifier = 1*( VCHAR - sep )

variable = "$" identifier / "${" identifier "}"
evaluate = "$" function-expression
