script = *( function-expression / function (";" / 2LWSP ) / comment / LWSP )

comment = "#" *OCTET LWSP

expression = function-expression / literal / variable / evaluate
function-expression = "(" [ LWSP ] function [ LWSP ] ")"
function = identifier [ SP expression *(SP expression) ]

; string
literal = DQUOTE *OCTET DQUOTE / *( ALPHA / DIGIT / "-" / "_" / "." )
; number
literal =/ 1*DIGIT
; bool
literal =/ "true" / "false"
; list
literal =/ "[" [LWSP] [ expression *( LWSP expression ) ] [LWSP] "]"
; empty
literal =/ "()"

identifier = 1*( VCHAR - LWSP )

variable = "$" ALPHA / "${" identifier "}"
evaluate = "$(" expression ")"
